# Generated by Django 4.1.5 on 2023-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end',
            field=models.IntegerField(null=True),
        ),
    ]
