# Generated by Django 4.1.5 on 2023-01-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staff_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='end',
        ),
    ]
