# Generated by Django 4.1.5 on 2023-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_staff_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="pic",
            field=models.ImageField(null=True, upload_to="profile_pic"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="exp",
            field=models.IntegerField(verbose_name="Experience"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="first",
            field=models.CharField(max_length=100, verbose_name="Enter First Name"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last",
            field=models.CharField(max_length=100, verbose_name="Enter Last Name"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="mail",
            field=models.EmailField(max_length=254, verbose_name="G-Mail"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="password",
            field=models.CharField(max_length=100, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="username",
            field=models.CharField(max_length=100, verbose_name="Username"),
        ),
    ]
